version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3030:3000"
    environment:
      - API_URL=http://localhost:4040
      - CLOUDFLARE_SITE_KEY=${CLOUDFLARE_SITE_KEY}
    depends_on:
      - backend

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "4040:4000"
    environment:
      - REDIS_URL=redis://redis:7070
      - CLOUDFLARE_SECRET_KEY=${CLOUDFLARE_SECRET_KEY}
    volumes:
      - ./backend/script:/app/script
    depends_on:
      - redis

  redis:
    image: redis:alpine
    ports:
      - "7070:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes

volumes:
  redis_data:
